exit codes and better error msg

diff --git a/.github/workflows/continuous-integration.yml b/.github/workflows/continuous-integration.yml
--- a/.github/workflows/continuous-integration.yml
+++ b/.github/workflows/continuous-integration.yml
@@ -56,4 +56,4 @@ jobs:
       - name: Build
         run: yarn build
       - name: Check
-        run: '[ -n "$(git status --porcelain)" ] && echo "::error::Build created a different bundle"'
+        run: '[ -n "$(git status --porcelain)" ] && (echo "::error::Build created a different bundle from the commited one" && exit 1) || exit 0'
